obsidian_entrypoint_path_str: VS-Wiki/Home.md   
site_name: 'Vampire Survivors Wiki'
html_url_prefix: '/VS-Wiki'
navbar_links:
    - name: Home
      link: index.html
toggles: 
    process_all: true
    features:
        styling:
            layout: documentation
            max_note_width: 45rem
        tags_page: 
            enabled: false
        create_index_from_dir_structure:
            enabled: false
        side_pane:
            left_pane:
                enabled: false
            right_pane:
                enabled: false
